name: batch730pm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  image_picker: ^1.0.0
  shared_preferences: ^2.3.0
  http: ^1.2.0
  dio: ^5.4.0
  url_launcher: ^6.3.0
  location: ^5.0.0
  app_settings: ^5.1.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^14.1.1
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/