name: batch730pm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  intl: ^0.19.0
  image_picker: ^1.0.0
  shared_preferences: ^2.3.0
  http: ^1.2.0
  dio: ^5.4.0
  url_launcher: ^6.3.0
  location: ^7.0.1
  app_settings: ^5.1.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/