name: batch730pm
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  intl: ^0.19.0
  image_picker: ^1.0.0
  shared_preferences: ^2.1.1
  http: ^1.2.2
  dio: ^5.4.0
  url_launcher: ^6.1.0
  location: ^7.0.1
  app_settings: ^5.1.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.0.0
  sign_in_with_apple: ^6.1.3
  google_maps_flutter: ^2.3.0
  flutter_polyline_points: ^2.1.0
  video_player: ^2.8.1
  intl_phone_field: ^3.2.0
  device_info_plus: ^11.1.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - videos/